In [1]:

# Setting up the workspace by importing all of the necessary libraries.
#from importlib import reload

import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')


In [2]:
def fix_placeholder(df=None, column=None ,placeholder=None, value=0):
    for item in placeholder:
        df.loc[df[column] == item, column]=value

#### Importing the data and combining two datasets
- dietdf contains information collected about each respondents dietary intake
- quesdf contains information obtained from a survey conducted on the respondents

We are joining both dataframes together using SEQN which will be renamed to id.

In [3]:
dietdf = pd.read_csv('data/diet.csv')
dietdf.head()

SEQN         WTDRD1         WTDR2D  DR1DRSTZ  DR1EXMER  DRABF  DRDINT  \
0  73557   16888.327864   12930.890649         1      49.0    2.0     2.0   
1  73558   17932.143865   12684.148869         1      59.0    2.0     2.0   
2  73559   59641.812930   39394.236709         1      49.0    2.0     2.0   
3  73560  142203.069917  125966.366442         1      54.0    2.0     2.0   
4  73561   59052.357033   39004.892993         1      63.0    2.0     2.0   

   DR1DBIH  DR1DAY  DR1LANG  ...  DRD370QQ  DRD370R  DRD370RQ  DRD370S  \
0      6.0     2.0      1.0  ...       NaN      NaN       NaN      NaN   
1      4.0     1.0      1.0  ...       NaN      2.0       NaN      2.0   
2     18.0     6.0      1.0  ...       NaN      NaN       NaN      NaN   
3     21.0     3.0      1.0  ...       NaN      NaN       NaN      NaN   
4     18.0     1.0      1.0  ...       NaN      2.0       NaN      2.0   

   DRD370SQ  DRD370T  DRD370TQ  DRD370U  DRD370UQ  DRD370V  
0       NaN      NaN       NaN      NaN       NaN      NaN  
1       NaN      2.0       NaN      2.0       NaN      2.0  
2       NaN      NaN       NaN      NaN       NaN      NaN  
3       NaN      NaN       NaN      NaN       NaN      NaN  
4       NaN      2.0       NaN      2.0       NaN      2.0  

[5 rows x 168 columns]

In [4]:
display(dietdf.head())
print(dietdf.shape)

SEQN         WTDRD1         WTDR2D  DR1DRSTZ  DR1EXMER  DRABF  DRDINT  \
0  73557   16888.327864   12930.890649         1      49.0    2.0     2.0   
1  73558   17932.143865   12684.148869         1      59.0    2.0     2.0   
2  73559   59641.812930   39394.236709         1      49.0    2.0     2.0   
3  73560  142203.069917  125966.366442         1      54.0    2.0     2.0   
4  73561   59052.357033   39004.892993         1      63.0    2.0     2.0   

   DR1DBIH  DR1DAY  DR1LANG  ...  DRD370QQ  DRD370R  DRD370RQ  DRD370S  \
0      6.0     2.0      1.0  ...       NaN      NaN       NaN      NaN   
1      4.0     1.0      1.0  ...       NaN      2.0       NaN      2.0   
2     18.0     6.0      1.0  ...       NaN      NaN       NaN      NaN   
3     21.0     3.0      1.0  ...       NaN      NaN       NaN      NaN   
4     18.0     1.0      1.0  ...       NaN      2.0       NaN      2.0   

   DRD370SQ  DRD370T  DRD370TQ  DRD370U  DRD370UQ  DRD370V  
0       NaN      NaN       NaN      NaN       NaN      NaN  
1       NaN      2.0       NaN      2.0       NaN      2.0  
2       NaN      NaN       NaN      NaN       NaN      NaN  
3       NaN      NaN       NaN      NaN       NaN      NaN  
4       NaN      2.0       NaN      2.0       NaN      2.0  

[5 rows x 168 columns]

(9813, 168)


In [5]:
dietdf.describe()

SEQN         WTDRD1         WTDR2D     DR1DRSTZ     DR1EXMER  \
count   9813.000000    9813.000000    8661.000000  9813.000000  8783.000000   
mean   78644.559971   31713.463364   35931.672555     1.472027    43.793351   
std     2938.592266   36061.598495   51017.340117     1.260325    20.535725   
min    73557.000000       0.000000       0.000000     1.000000     2.000000   
25%    76092.000000    8731.762120    7255.716712     1.000000    25.000000   
50%    78643.000000   19276.118837   17874.047830     1.000000    49.000000   
75%    81191.000000   42490.159621   44897.265674     1.000000    59.000000   
max    83731.000000  267526.890966  818626.657231     5.000000    91.000000   

             DRABF       DRDINT      DR1DBIH       DR1DAY      DR1LANG  ...  \
count  8661.000000  8661.000000  8706.000000  8783.000000  8797.000000  ...   
mean      1.984528     1.874495    16.176085     4.501423     1.156303  ...   
std       0.123426     0.331310    11.804355     2.184283     0.555685  ...   
min       1.000000     1.000000   -31.000000     1.000000     1.000000  ...   
25%       2.000000     2.000000     7.000000     3.000000     1.000000  ...   
50%       2.000000     2.000000    16.000000     5.000000     1.000000  ...   
75%       2.000000     2.000000    23.000000     6.000000     1.000000  ...   
max       2.000000     2.000000    74.000000     7.000000     6.000000  ...   

        DRD370QQ      DRD370R    DRD370RQ      DRD370S   DRD370SQ  \
count  61.000000  5121.000000  171.000000  5121.000000  27.000000   
mean    1.557377     1.966608    1.766082     1.994728   2.481481   
std     1.443660     0.179675    1.184814     0.072427   2.651130   
min     1.000000     1.000000    1.000000     1.000000   1.000000   
25%     1.000000     2.000000    1.000000     2.000000   1.000000   
50%     1.000000     2.000000    1.000000     2.000000   1.000000   
75%     1.000000     2.000000    2.000000     2.000000   2.500000   
max    10.000000     2.000000    8.000000     2.000000  10.000000   

           DRD370T     DRD370TQ      DRD370U    DRD370UQ  DRD370V  
count  5121.000000  1318.000000  5121.000000  317.000000   5120.0  
mean      1.742628     2.622155     1.938098    2.400631      2.0  
std       0.437229     2.793016     0.241001    2.997953      0.0  
min       1.000000     1.000000     1.000000    1.000000      2.0  
25%       1.000000     1.000000     2.000000    1.000000      2.0  
50%       2.000000     2.000000     2.000000    2.000000      2.0  
75%       2.000000     3.000000     2.000000    2.000000      2.0  
max       2.000000    30.000000     2.000000   30.000000      2.0  

[8 rows x 168 columns]

In [6]:
quesdf = pd.read_csv('data/questionnaire.csv')
quesdf.head()

SEQN  ACD011A  ACD011B  ACD011C  ACD040  ACD110  ALQ101  ALQ110  ALQ120Q  \
0  73557      1.0      NaN      NaN     NaN     NaN     1.0     NaN      1.0   
1  73558      1.0      NaN      NaN     NaN     NaN     1.0     NaN      7.0   
2  73559      1.0      NaN      NaN     NaN     NaN     1.0     NaN      0.0   
3  73560      1.0      NaN      NaN     NaN     NaN     NaN     NaN      NaN   
4  73561      1.0      NaN      NaN     NaN     NaN     1.0     NaN      0.0   

   ALQ120U  ...  WHD080U  WHD080L  WHD110  WHD120  WHD130  WHD140  WHQ150  \
0      3.0  ...      NaN     40.0   270.0   200.0    69.0   270.0    62.0   
1      1.0  ...      NaN      NaN   240.0   250.0    72.0   250.0    25.0   
2      NaN  ...      NaN      NaN   180.0   190.0    70.0   228.0    35.0   
3      NaN  ...      NaN      NaN     NaN     NaN     NaN     NaN     NaN   
4      NaN  ...      NaN      NaN   150.0   135.0    67.0   170.0    60.0   

   WHQ030M  WHQ500  WHQ520  
0      NaN     NaN     NaN  
1      NaN     NaN     NaN  
2      NaN     NaN     NaN  
3      3.0     3.0     3.0  
4      NaN     NaN     NaN  

[5 rows x 953 columns]

#### This Data Set has only a few items we need, so we will isolate those for our analysis

In [7]:
quesdf = quesdf[['SEQN', 'DIQ010', 'DIQ160']]
quesdf.head()

SEQN  DIQ010  DIQ160
0  73557     1.0     NaN
1  73558     1.0     NaN
2  73559     1.0     NaN
3  73560     2.0     NaN
4  73561     2.0     2.0

#### In preparation for joining, we will rename the index of one of the DF's

In [8]:
quesdf.rename({'SEQN':'SEQN1'}, axis=1, inplace=True);
quesdf.head()

SEQN1  DIQ010  DIQ160
0  73557     1.0     NaN
1  73558     1.0     NaN
2  73559     1.0     NaN
3  73560     2.0     NaN
4  73561     2.0     2.0

#### Many of the columns are not necessary for our analysis, so we will drop them here.
- 'SEQN1' is the same as 'SEQN' and is not necessary after the join
- 'DR1EXMER' is an identifier for the interviewer
- 'DR1DBIH' is the number of days elapsed between the exam and interview
- 'DR1LANG' is the language used by the respondent for the interview
- 'DR1MNRSP' is the person who answered the questions, subject or caretaker
- 'DR1HELPD' identifies who helped answer the questions, if anyone

In [9]:
df = pd.merge(dietdf, quesdf, left_on='SEQN', right_on='SEQN1', how='left')
labels = [
    'SEQN1',
    'DR1EXMER',
    'DR1DBIH',
    'DR1LANG',
    'DR1MNRSP',
    'DR1HELPD'
]

df.drop(labels, axis=1, inplace=True)
df.rename(columns={'SEQN':'id'}, inplace=True)
df.head()

id         WTDRD1         WTDR2D  DR1DRSTZ  DRABF  DRDINT  DR1DAY  \
0  73557   16888.327864   12930.890649         1    2.0     2.0     2.0   
1  73558   17932.143865   12684.148869         1    2.0     2.0     1.0   
2  73559   59641.812930   39394.236709         1    2.0     2.0     6.0   
3  73560  142203.069917  125966.366442         1    2.0     2.0     3.0   
4  73561   59052.357033   39004.892993         1    2.0     2.0     1.0   

   DBQ095Z  DBD100  DRQSPREP  ...  DRD370RQ  DRD370S  DRD370SQ  DRD370T  \
0      3.0     2.0       4.0  ...       NaN      NaN       NaN      NaN   
1      1.0     2.0       3.0  ...       NaN      2.0       NaN      2.0   
2      1.0     1.0       2.0  ...       NaN      NaN       NaN      NaN   
3      1.0     1.0       3.0  ...       NaN      NaN       NaN      NaN   
4      4.0     NaN       4.0  ...       NaN      2.0       NaN      2.0   

   DRD370TQ  DRD370U  DRD370UQ  DRD370V  DIQ010  DIQ160  
0       NaN      NaN       NaN      NaN     1.0     NaN  
1       NaN      2.0       NaN      2.0     1.0     NaN  
2       NaN      NaN       NaN      NaN     1.0     NaN  
3       NaN      NaN       NaN      NaN     2.0     NaN  
4       NaN      2.0       NaN      2.0     2.0     2.0  

[5 rows x 165 columns]

In [10]:
df.describe()

id         WTDRD1         WTDR2D     DR1DRSTZ        DRABF  \
count   9813.000000    9813.000000    8661.000000  9813.000000  8661.000000   
mean   78644.559971   31713.463364   35931.672555     1.472027     1.984528   
std     2938.592266   36061.598495   51017.340117     1.260325     0.123426   
min    73557.000000       0.000000       0.000000     1.000000     1.000000   
25%    76092.000000    8731.762120    7255.716712     1.000000     2.000000   
50%    78643.000000   19276.118837   17874.047830     1.000000     2.000000   
75%    81191.000000   42490.159621   44897.265674     1.000000     2.000000   
max    83731.000000  267526.890966  818626.657231     5.000000     2.000000   

            DRDINT       DR1DAY      DBQ095Z       DBD100     DRQSPREP  ...  \
count  8661.000000  8783.000000  8783.000000  5399.000000  8783.000000  ...   
mean      1.874495     4.501423     3.578504     1.652899     3.178754  ...   
std       0.331310     2.184283    11.600264     0.811360     1.182280  ...   
min       1.000000     1.000000     1.000000     1.000000     1.000000  ...   
25%       2.000000     3.000000     1.000000     1.000000     3.000000  ...   
50%       2.000000     5.000000     1.000000     1.000000     3.000000  ...   
75%       2.000000     6.000000     4.000000     2.000000     4.000000  ...   
max       2.000000     7.000000    99.000000     9.000000     9.000000  ...   

         DRD370RQ      DRD370S   DRD370SQ      DRD370T     DRD370TQ  \
count  171.000000  5121.000000  27.000000  5121.000000  1318.000000   
mean     1.766082     1.994728   2.481481     1.742628     2.622155   
std      1.184814     0.072427   2.651130     0.437229     2.793016   
min      1.000000     1.000000   1.000000     1.000000     1.000000   
25%      1.000000     2.000000   1.000000     1.000000     1.000000   
50%      1.000000     2.000000   1.000000     2.000000     2.000000   
75%      2.000000     2.000000   2.500000     2.000000     3.000000   
max      8.000000     2.000000  10.000000     2.000000    30.000000   

           DRD370U    DRD370UQ  DRD370V       DIQ010       DIQ160  
count  5121.000000  317.000000   5120.0  9421.000000  6086.000000  
mean      1.938098    2.400631      2.0     1.946609     1.964673  
std       0.241001    2.997953      0.0     0.348510     0.328189  
min       1.000000    1.000000      2.0     1.000000     1.000000  
25%       2.000000    1.000000      2.0     2.000000     2.000000  
50%       2.000000    2.000000      2.0     2.000000     2.000000  
75%       2.000000    2.000000      2.0     2.000000     2.000000  
max       2.000000   30.000000      2.0     9.000000     9.000000  

[8 rows x 165 columns]

#### Looking at the data to see if any cleaning is necessary

In [11]:
df.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9813 entries, 0 to 9812
Data columns (total 165 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   id        9813 non-null   int64  
 1   WTDRD1    9813 non-null   float64
 2   WTDR2D    8661 non-null   float64
 3   DR1DRSTZ  9813 non-null   int64  
 4   DRABF     8661 non-null   float64
 5   DRDINT    8661 non-null   float64
 6   DR1DAY    8783 non-null   float64
 7   DBQ095Z   8783 non-null   float64
 8   DBD100    5399 non-null   float64
 9   DRQSPREP  8783 non-null   float64
 10  DR1STY    8783 non-null   float64
 11  DR1SKY    1448 non-null   float64
 12  DRQSDIET  8783 non-null   float64
 13  DRQSDT1   523 non-null    float64
 14  DRQSDT2   131 non-null    float64
 15  DRQSDT3   121 non-null    float64
 16  DRQSDT4   37 non-null     float64
 17  DRQSDT5   0 non-null      float64
 18  DRQSDT6   4 non-null      float64
 19  DRQSDT7   146 non-null    float64
 20  DRQSDT8   34 non-null     flo

In [15]:
for col in df.columns:
    print(f'{col}')
    print(df[col].nunique())

id
9813
WTDRD1
7931
WTDR2D
7123
DR1DRSTZ
4
DRABF
2
DRDINT
2
DR1DAY
7
DBQ095Z
5
DBD100
4
DRQSPREP
5
DR1STY
3
DR1SKY
4
DRQSDIET
3
DRQSDT1
1
DRQSDT2
1
DRQSDT3
1
DRQSDT4
1
DRQSDT5
0
DRQSDT6
1
DRQSDT7
1
DRQSDT8
1
DRQSDT9
1
DRQSDT10
1
DRQSDT11
1
DRQSDT12
1
DRQSDT91
1
DR1TNUMF
45
DR1TKCAL
3132
DR1TPROT
6206
DR1TCARB
7647
DR1TSUGR
6919
DR1TFIBE
539
DR1TTFAT
6292
DR1TSFAT
7750
DR1TMFAT
7734
DR1TPFAT
7489
DR1TCHOL
982
DR1TATOC
2036
DR1TATOA
621
DR1TRET
1353
DR1TVARA
1715
DR1TACAR
1472
DR1TBCAR
3309
DR1TCRYP
585
DR1TLYCO
3885
DR1TLZ
2689
DR1TVB1
2866
DR1TVB2
3344
DR1TNIAC
7675
DR1TVB6
3459
DR1TFOLA
1100
DR1TFA
784
DR1TFF
680
DR1TFDFE
1424
DR1TCHL
4448
DR1TVB12
1464
DR1TB12A
694
DR1TVC
2325
DR1TVD
317
DR1TVK
2441
DR1TCALC
2135
DR1TPHOS
2460
DR1TMAGN
745
DR1TIRON
2762
DR1TZINC
2228
DR1TCOPP
2189
DR1TSODI
4487
DR1TPOTA
3678
DR1TSELE
2305
DR1TCAFF
630
DR1TTHEO
407
DR1TALCO
408
DR1TMOIS
8428
DR1TS040
1613
DR1TS060
1151
DR1TS080
1082
DR1TS100
1609
DR1TS120
2403
DR1TS140
4058
DR1TS160
7213
DR1TS180
6073

#### There are numerous NaN's, so we will deal with them here

In [13]:
nan_list_1 = [
    'DRABF',
    'DRDINT',
    'DR1DAY',
    'DBQ095Z',
    'DBD100',
    'DRQSPREP',
    'DR1STY',
    'DR1SKY',
    'DRQSDIET',
    'DRQSDT1',
    'DRQSDT2',
    'DRQSDT3',
    'DRQSDT4',
    'DRQSDT5', 
    'DRQSDT6',
    'DRQSDT7',
    'DRQSDT8',
    'DRQSDT9',
    'DRQSDT10',
    'DRQSDT11',
    'DRQSDT12',
    'DRQSDT91',
    'DR1TNUMF'
]

In [14]:
for item in nan_list_1:
    df.loc[df[item] > 91] = 0

In [15]:
df.fillna(0,inplace=True);

In [16]:
for col in df.columns:
    print(f'{col}: ')
    print(df[col].unique())


id
[73557 73558 73559 ... 83729 83730 83731]

WTDRD1
[16888.327864 17932.143865 59641.81293  ... 14146.781331 38750.761193
 15272.505199]

WTDR2D
[12930.890649 12684.148869 39394.236709 ... 51815.103262 10401.78117
  4339.132077]

DR1DRSTZ
[1 4 5 0 2]

DRABF
[2. 1. 0.]

DRDINT
[2. 1. 0.]

DR1DAY
[2. 1. 6. 3. 7. 4. 0. 5.]

DBQ095Z
[3. 1. 4. 0. 2.]

DBD100
[2. 1. 0. 3. 9.]

DRQSPREP
[4. 3. 2. 1. 0. 9.]

DR1STY
[2. 1. 0. 9.]

DR1SKY
[0. 1. 2. 3.]

DRQSDIET
[2. 1. 0. 9.]

DRQSDT1
[0. 1.]

DRQSDT2
[0. 2.]

DRQSDT3
[0. 3.]

DRQSDT4
[0. 4.]

DRQSDT5
[0.]

DRQSDT6
[0. 6.]

DRQSDT7
[0. 7.]

DRQSDT8
[0. 8.]

DRQSDT9
[0. 9.]

DRQSDT10
[ 0. 10.]

DRQSDT11
[ 0. 11.]

DRQSDT12
[ 0. 12.]

DRQSDT91
[ 0. 91.]

DR1TNUMF
[11.  8. 27. 19.  7. 17. 10. 21. 14. 30. 15. 12.  0. 35.  6. 18. 13. 22.
 23. 16.  9. 36. 31. 24. 29. 20.  4.  5. 25. 33.  3. 28. 43. 26. 32. 34.
  2.  1. 37. 40. 39. 38. 45. 46. 41. 49.]

DR1TKCAL
[1574. 5062. 1743. ... 4680.  905. 4687.]

DR1TPROT
[ 43.63 338.13  64.61 ... 223.32  47.

 7.5800e+02 5.3700e+02 2.7350e+03 5.7500e+02 9.4200e+02]

DR1TLYCO
[1398.    0.  515. ... 1923. 6759. 6190.]

DR1TLZ
[ 430.  899.  300. ... 5538. 3255. 3795.]

DR1TVB1
[1.057 4.178 1.648 ... 3.17  3.285 3.922]

DR1TVB2
[1.216 5.168 1.747 ... 6.575 3.946 4.371]

DR1TNIAC
[11.804 65.396 18.342 ... 11.309 31.59  19.119]

DR1TVB6
[0.951 4.415 1.906 ... 0.413 4.418 4.381]

DR1TFOLA
[ 285. 1243.  423. ... 1267. 1021. 1161.]

DR1TFA
[6.600e+01 6.010e+02 2.900e+02 1.260e+02 3.890e+02 7.600e+01 0.000e+00
 3.360e+02 8.700e+01 1.450e+02 2.280e+02 1.740e+02 8.100e+01 3.480e+02
 1.600e+02 1.050e+02 1.930e+02 1.690e+02 3.400e+02 4.500e+01 1.900e+01
 5.800e+01 1.020e+02 1.650e+02 2.810e+02 4.000e+00 8.000e+01 1.570e+02
 3.800e+01 6.000e+01 9.300e+01 3.040e+02 1.810e+02 5.060e+02 7.590e+02
 1.620e+02 7.100e+01 4.860e+02 1.520e+02 5.710e+02 2.680e+02 1.880e+02
 5.300e+01 1.500e+02 5.690e+02 1.580e+02 2.500e+02 2.020e+02 4.700e+01
 2.440e+02 1.030e+02 2.100e+01 1.730e+02 2.110e+02 4.200e+01 4.900e+01
 4

 1.622e+02]

DR1TMOIS
[2701.79 6779.99 3766.7  ... 1304.06 2406.7  2190.  ]

DR1TS040
[0.219 1.872 0.358 ... 1.555 1.171 1.466]

DR1TS060
[0.099 1.16  0.128 ... 2.211 0.862 1.354]

DR1TS080
[0.103 0.802 0.371 ... 1.315 1.16  0.821]

DR1TS100
[0.153 1.286 0.455 ... 1.122 1.238 1.343]

DR1TS120
[0.346 1.297 3.008 ... 1.594 1.446 7.674]

DR1TS140
[1.221 6.516 2.067 ... 4.764 6.018 2.251]

DR1TS160
[ 9.694 27.952 10.691 ... 10.764 16.753 14.016]

DR1TS180
[ 5.408 12.107  7.497 ...  9.488 18.605  6.412]

DR1TM161
[1.173 2.208 0.531 ... 4.231 1.551 3.411]

DR1TM181
[16.796 32.429 19.91  ... 42.883 14.565 23.428]

DR1TM201
[0.121 0.086 0.164 ... 1.127 1.004 1.07 ]

DR1TM221
[1.000e-03 0.000e+00 5.000e-03 3.000e-03 6.000e-03 2.500e-02 3.700e-02
 1.600e-02 1.800e-02 4.000e-03 4.800e-02 1.500e-02 2.000e-03 8.000e-03
 1.000e-01 3.000e-02 1.000e-02 7.000e-03 1.130e-01 3.300e-02 7.400e-02
 1.700e-02 9.200e-02 1.300e-02 1.100e-02 2.700e-02 9.000e-03 6.800e-02
 6.100e-02 3.800e-02 2.000e-02 9.700e-02


DRD350DQ
[ 0.  1.  2.  3.  5.  6.  4. 10.  8.]

DRD350E
[0. 2. 1.]

DRD350EQ
[0. 1. 4. 3. 2. 5. 6.]

DRD350F
[0. 2. 1.]

DRD350FQ
[ 0.  1.  7.  2.  3.  5.  4. 11.  8.  6. 10. 20.]

DRD350G
[0. 1. 2.]

DRD350GQ
[ 0.  1.  2.  5.  3.  4.  7. 10. 12.]

DRD350H
[0. 1. 2.]

DRD350HQ
[ 0.  1.  2.  3.  4.  5. 10. 16.  8.  7.  6. 20. 17. 15. 12. 11. 30. 13.
  9.]

DRD350I
[0. 2. 1.]

DRD350IQ
[ 0.  1.  2.  3.  4.  5.  6. 10.  8.]

DRD350J
[0. 2. 1.]

DRD350JQ
[0. 1. 2. 4.]

DRD350K
[0. 2.]

DRD360
[2. 1. 0. 9. 7.]

DRD370A
[0. 2. 1.]

DRD370AQ
[ 0.  1.  2.  3.  8.  4.  6.  5. 15. 10.  7.  9. 12.]

DRD370B
[0. 2. 1.]

DRD370BQ
[ 0.  1.  2. 10.  5.  3.  4. 15. 12. 25.  6.  8. 24.  7.  9. 16. 20. 11.]

DRD370C
[0. 2. 1.]

DRD370CQ
[ 0.  3.  4.  2.  1.  5. 14.  8.]

DRD370D
[0. 2. 1.]

DRD370DQ
[ 0.  2.  1.  4.  5.  3. 12.  6.  8.  7. 10. 15.]

DRD370E
[0. 2. 1.]

DRD370EQ
[ 0.  1.  2.  3.  4.  6. 10.  8.  5. 15. 14.]

DRD370F
[0. 2. 1.]

DRD370FQ
[ 0.  1.  2.  4.  3.  5.  8. 12.  6. 10.]

DRD370G

In [17]:
df.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9813 entries, 0 to 9812
Data columns (total 165 columns):
id          9813 non-null int64
WTDRD1      9813 non-null float64
WTDR2D      9813 non-null float64
DR1DRSTZ    9813 non-null int64
DRABF       9813 non-null float64
DRDINT      9813 non-null float64
DR1DAY      9813 non-null float64
DBQ095Z     9813 non-null float64
DBD100      9813 non-null float64
DRQSPREP    9813 non-null float64
DR1STY      9813 non-null float64
DR1SKY      9813 non-null float64
DRQSDIET    9813 non-null float64
DRQSDT1     9813 non-null float64
DRQSDT2     9813 non-null float64
DRQSDT3     9813 non-null float64
DRQSDT4     9813 non-null float64
DRQSDT5     9813 non-null float64
DRQSDT6     9813 non-null float64
DRQSDT7     9813 non-null float64
DRQSDT8     9813 non-null float64
DRQSDT9     9813 non-null float64
DRQSDT10    9813 non-null float64
DRQSDT11    9813 non-null float64
DRQSDT12    9813 non-null float64
DRQSDT91    9813 non-null float64
DR1TNUMF    

#### Our target, DIQ010 has multiple values.  We will drop the few that were refused, didn't know or were missing,

we will also drop the boarderline responses to eliminate some grey area for our purposes.

In [18]:
df.drop(df[df['DIQ010'] == 3].index, inplace = True)
fix_placeholder(df, 'DIQ010', [2, 7, 9], 0)
df.head()

id         WTDRD1         WTDR2D  DR1DRSTZ  DRABF  DRDINT  DR1DAY  \
0  73557   16888.327864   12930.890649         1    2.0     2.0     2.0   
1  73558   17932.143865   12684.148869         1    2.0     2.0     1.0   
2  73559   59641.812930   39394.236709         1    2.0     2.0     6.0   
3  73560  142203.069917  125966.366442         1    2.0     2.0     3.0   
4  73561   59052.357033   39004.892993         1    2.0     2.0     1.0   

   DBQ095Z  DBD100  DRQSPREP   ...    DRD370RQ  DRD370S  DRD370SQ  DRD370T  \
0      3.0     2.0       4.0   ...         0.0      0.0       0.0      0.0   
1      1.0     2.0       3.0   ...         0.0      2.0       0.0      2.0   
2      1.0     1.0       2.0   ...         0.0      0.0       0.0      0.0   
3      1.0     1.0       3.0   ...         0.0      0.0       0.0      0.0   
4      4.0     0.0       4.0   ...         0.0      2.0       0.0      2.0   

   DRD370TQ  DRD370U  DRD370UQ  DRD370V  DIQ010  DIQ160  
0       0.0      0.0       0.0      0.0     1.0     0.0  
1       0.0      2.0       0.0      2.0     1.0     0.0  
2       0.0      0.0       0.0      0.0     1.0     0.0  
3       0.0      0.0       0.0      0.0     0.0     0.0  
4       0.0      2.0       0.0      2.0     0.0     2.0  

[5 rows x 165 columns]

In [19]:
df.DIQ010.unique()

array([1., 0.])

In [20]:
fix_placeholder(df,'DR1TWS', [0, 99], 1)
fix_placeholder(df,'DBD100', [9], 3)
fix_placeholder(df,'DRQSPREP', [9], 3)
fix_placeholder(df,'DR1STY', [9], 2)
fix_placeholder(df,'DRQSDIET', [9], 2)
fix_placeholder(df,'DR1.300', [9], 2)
fix_placeholder(df,'DRD340', [7, 9, 0], 2)
fix_placeholder(df,'DRD360', [7, 9, 0], 2)


In [21]:
df.DIQ010.unique()

array([1., 0.])

In [22]:
df.DIQ160.unique()

array([0., 2., 1., 9.])

In [23]:
fix_placeholder(df, 'DIQ160', [2, 9], 0)

In [24]:
df.DIQ160.unique()

array([0., 1.])

In [25]:
df.DIQ010.unique()

array([1., 0.])

#### Other than the NaN's, the data was very clean.  We will save it for our modeling.

In [26]:
df.drop('DIQ160', axis=1).to_csv('DIQ010_Target.csv',index=False)
df.drop('DIQ010', axis=1).to_csv('DIQ160_Target.csv',index=False)